apiVersion: v1
kind: Pod
metadata:
 name: sample10
spec:
 containers:
   - image: nginx
     name: client
     lifecycle:
       preStop:
         httpGet:
         port: 8080
         path: /shutdown